### ISSUE TITLE
Error while executing Unit Test

### ISSUE THREAD

**Issue by sauravexodus** [jlien/pocketsphinx-sinatra#1]
When I executed this 
```bash
$ ruby test/transcribe_test.rb
``` 
I got the following error. Any help would be appreciated

> 1) Error:
> TranscribeTest#test_transcribe_post:
> NoMethodError: undefined method `bytesize' for Rack::Utils:Module
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:154:in `block in finish'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:154:in `each'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:154:in `inject'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:154:in `finish'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:918:in `call!'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1@global/gems/rack-2.0.1/lib/rack/null_logger.rb:9:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1@global/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1@global/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/mock_session.rb:30:in `request'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:244:in `process_request'
>     /Users/Saurav/.rvm/gems/ruby-2.3.1/gems/rack-test-0.6.3/lib/rack/test.rb:67:in `post'
>     test/transcribe_test.rb:14:in `test_transcribe_post'
> 
> 1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
>

**Comment by sauravexodus** [comment]
Figured out that this was a problem with the new `rack 2.0.1` gem. Reverting back to `rack 1.6.5` solved the problem
